version: "3.8"
services:
  doble-pipeline:
    image: john4064/doble-pipeline:latest
    container_name: doble-pipeline
    restart: unless-stopped
    environment:
      - apiKey=${apiKey}
      - dbPass=${dbPass}
      - dbUrl=${dbUrl}
      - dbUser=${dbUser}
      - googleApiKey=${googleApiKey}
      - keyAlias=${keyAlias}
      - jksPass=${jksPass}
    ports:
      - "8443:8443"   # change if your app listens on a different port
    volumes:
      - ./mnt/user/applications/pipeline:/data
